name: fall_detection_app
description: A Fall Detection Mobile App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  supabase_flutter: ^2.8.4
  flutter:
    sdk: flutter
  http: ^1.3.0
  file_picker: ^9.2.1 
  async: ^2.12.0
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  vm_service: ^14.3.1

flutter:
  uses-material-design: true
